server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: msvc-students
          uri: lb://msvc-students:8081
          predicates:
            - Path=/api/practica/**
        - id: msvc-students
          uri: lb://msvc-students:8081
          predicates:
            - Path=/api/ejercicio/**
        - id: msvc-students
          uri: lb://msvc-students:8081
          predicates:
            - Path=/api/opcion/**

        - id: msvc-administration
          uri: lb://msvc-administration:8082
          predicates:
            - Path=/api/categoria/**
        - id: msvc-administration
          uri: lb://msvc-administration:8082
          predicates:
            - Path=/api/examen/**
        - id: msvc-administration
          uri: lb://msvc-administration:8082
          predicates:
            - Path=/api/problema/**
        - id: msvc-administration
          uri: lb://msvc-administration:8082
          predicates:
            - Path=/api/tabla/**

        - id: msvc-eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters: SetPath=/
        - id: msvc-eureka-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: msvc-gateway
          uri: http://localhost:8080
          predicates:
            - Path=/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/labsql-microservices-realm
          jwk-set-uri: http://localhost:9090/realms/labsql-microservices-realm/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: api-gateway
      principle-attribute: preferred_username

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    root: INFO

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: false